### ISSUE TITLE
Bug report on main 11/1/2024: Cannot read properties of undefined (reading 'evidenceLink')

### ISSUE THREAD

**Issue by gvelez17** [Cooperation-org/linked-claims-author#162]
![Image](https://github.com/user-attachments/assets/d7fd7db7-1593-4bc3-af9a-e198123d7b09)

at view credential link

https://opencreds.net/view/1j26D_M0TIpcBIvZ0x4ls2Jkr0QWlJl4E#step0

We should gently handle changes to schema please

we may want evidenceLink again later

**Comment by 0marSalah** [comment]
yeah i already did that i am using the local urls since users still in form process but this is in the view so we dont have it anymore 

(we could use localstorage but it will be hard to store the files itself it have limit to 5mb, however we can use indexDB and use it smoothly)

but anyway, i guess the problem resolved inn dev branch i will check again

**Comment by dev-mhany** [comment]
issue resolved
